site_name: Conference Site
nav:
    - Home: index.md
    - 1 lab:
        - Lab 1: lab1.md
    - 2 lab:
        - Lab 2: lab2.md
    - 3 lab:
        - Lab 3: lab3.md
    - Leetcode:
        - Leetcode: leetcode.md
theme: material