site_name: Warriors Project Documentation
nav:
  - Home: index.md
  - API Endpoints:
      - Skills Endpoint: app/skills.md
      - Warriors with Professions: app/warriors_professions.md
      - Warriors with Skills: app/warriors_skills.md
  - User Guide:
      - Registration: app/registration.md
      - Authentication: app/authentication.md
      - User Account Management: app/account_management.md